/**
 * Generated by scripts/generate-gi-coordinates.mjs.
 *
 * Do not edit this file directly. Use gi-coordinate-overrides.json for
 * verified manual corrections.
 */
import type { GiCoordinate } from "../types";

export const GI_COORDINATES_GENERATED_AT =
  "2026-08-06T09:00:46.283Z";

export const GI_COORDINATES: Record<string, GiCoordinate> =
  {
  "150KV AMLAPURA": {
    "latitude": -8.4481405,
    "longitude": 115.5878436,
    "precision": "exact",
    "displayName": "Gardu Induk Amlapura · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV ANTOSARI": {
    "latitude": -8.5163811,
    "longitude": 115.0148094,
    "precision": "exact",
    "displayName": "Gardu Induk Antosari · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BABADAN": {
    "latitude": -7.3889367,
    "longitude": 112.6753226,
    "precision": "exact",
    "displayName": "Gardu Induk Babadan",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BABAT": {
    "latitude": -7.1232971,
    "longitude": 112.1474209,
    "precision": "exact",
    "displayName": "Gardu Induk Babat · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BALONGBENDO": {
    "latitude": -7.4128967,
    "longitude": 112.5578116,
    "precision": "exact",
    "displayName": "Gardu Induk Balongbendo · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BAMBE": {
    "latitude": -7.3421925,
    "longitude": 112.664064,
    "precision": "exact",
    "displayName": "Gardu Induk Bambe · PLN · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BANARAN": {
    "latitude": -7.836582,
    "longitude": 112.0326284,
    "precision": "exact",
    "displayName": "Gardu Induk Banaran · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BANGIL": {
    "latitude": -7.6037974,
    "longitude": 112.7762847,
    "precision": "exact",
    "displayName": "Gardu Induk Bangil · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BANGKALAN": {
    "latitude": -7.0571027,
    "longitude": 112.7932737,
    "precision": "exact",
    "displayName": "Gardu Induk Bangkalan · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BANYUWANGI": {
    "latitude": -8.1887912,
    "longitude": 114.3555199,
    "precision": "exact",
    "displayName": "Gardu Induk Banyuwangi · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BATURITI": {
    "latitude": -8.257739,
    "longitude": 115.1610142,
    "precision": "exact",
    "displayName": "Gardu Induk Baturiti · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BOJONEGORO": {
    "latitude": -7.1759899,
    "longitude": 111.8671877,
    "precision": "exact",
    "displayName": "Gardu Induk Bojonegoro · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BONDOWOSO": {
    "latitude": -7.9376566,
    "longitude": 113.8334736,
    "precision": "exact",
    "displayName": "Gardu Induk Bondowoso · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BUDURAN": {
    "latitude": -7.422985,
    "longitude": 112.721433,
    "precision": "exact",
    "displayName": "Gardu Induk Buduran · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BULUKANDANG": {
    "latitude": -7.700547,
    "longitude": 112.6875964,
    "precision": "exact",
    "displayName": "Gardu Induk Bulukandang · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV BUNGAH": {
    "latitude": -7.0930088,
    "longitude": 112.6000184,
    "precision": "exact",
    "displayName": "Gardu Induk Bungah · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV CERME": {
    "latitude": -7.1822019,
    "longitude": 112.5776503,
    "precision": "exact",
    "displayName": "Gardu Induk Cerme · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV DARMOGRANDE": {
    "latitude": -7.2882327,
    "longitude": 112.6744149,
    "precision": "exact",
    "displayName": "Gardu Induk Darmogrande · PT Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV DRIYOREJO": {
    "latitude": -7.3687406,
    "longitude": 112.5998469,
    "precision": "exact",
    "displayName": "Gardu Induk Driyorejo · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV GEMBONG": {
    "latitude": -7.241521,
    "longitude": 112.7502789,
    "precision": "exact",
    "displayName": "GIS Gembong · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV GENDING": {
    "latitude": -7.7970236,
    "longitude": 113.3135529,
    "precision": "exact",
    "displayName": "Gardu Induk Gending · PLN · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV GENTENG": {
    "latitude": -8.3868442,
    "longitude": 114.1640197,
    "precision": "exact",
    "displayName": "Gardu Induk Genteng · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV GIANYAR": {
    "latitude": -8.5618733,
    "longitude": 115.3346076,
    "precision": "exact",
    "displayName": "Gardu Induk Gianyar · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV GILIMANUK": {
    "latitude": -8.174874,
    "longitude": 114.4416848,
    "precision": "exact",
    "displayName": "Gardu Induk Gilimanuk · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV GULUK GULUK": {
    "latitude": -7.0659462,
    "longitude": 113.6858886,
    "precision": "exact",
    "displayName": "Gardu Induk Guluk-Guluk · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV GUNUNGSARI": {
    "latitude": -7.3034147,
    "longitude": 112.7071752,
    "precision": "exact",
    "displayName": "GIS Gunungsari · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV JATIGEDONG": {
    "latitude": -7.4378165,
    "longitude": 112.2500116,
    "precision": "exact",
    "displayName": "Gardu Induk Jatigedong · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV JEMBER": {
    "latitude": -8.1928341,
    "longitude": 113.6981551,
    "precision": "exact",
    "displayName": "Gardu Induk Jember · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV JOMBANG": {
    "latitude": -7.5389628,
    "longitude": 112.2085809,
    "precision": "exact",
    "displayName": "Gardu Induk Jombang · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KALISARI": {
    "latitude": -6.9918658,
    "longitude": 110.4051451,
    "precision": "exact",
    "displayName": "Gardu Induk Kalisari · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KAPAL": {
    "latitude": -8.5825929,
    "longitude": 115.1823059,
    "precision": "exact",
    "displayName": "Gardu Induk Kapal · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KARANGPILANG": {
    "latitude": -7.3263689,
    "longitude": 112.650998,
    "precision": "exact",
    "displayName": "GIS Karangpilang · PT Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KEBONAGUNG": {
    "latitude": -8.0214043,
    "longitude": 112.6169953,
    "precision": "exact",
    "displayName": "Gardu Induk Kebonagung · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KEDINDING": {
    "latitude": -7.2229071,
    "longitude": 112.7815341,
    "precision": "exact",
    "displayName": "Gardu Induk Kedinding · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KENJERAN": {
    "latitude": -7.2549265,
    "longitude": 112.7713769,
    "precision": "exact",
    "displayName": "Gardu Induk Kenjeran · PT Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KERTOSONO": {
    "latitude": -7.6148983,
    "longitude": 112.0978296,
    "precision": "exact",
    "displayName": "Gardu Induk Kertosono · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KIS": {
    "latitude": -7.545281,
    "longitude": 112.7715772,
    "precision": "exact",
    "displayName": "Gardu Induk KIS",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KRAKSAAN": {
    "latitude": -7.7796234,
    "longitude": 113.4268628,
    "precision": "exact",
    "displayName": "Gardu Induk Kraksaan · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KREMBANGAN": {
    "latitude": -7.2286916,
    "longitude": 112.7216188,
    "precision": "exact",
    "displayName": "GIS Krembangan · PT Perusahaan Listrik Negara · transition",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KUBU": {
    "latitude": -8.2037849,
    "longitude": 115.497912,
    "precision": "exact",
    "displayName": "Gardu Induk Kubu · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV KUPANG": {
    "latitude": -7.2685146,
    "longitude": 112.7355097,
    "precision": "exact",
    "displayName": "GIS Kupang · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV LAMONGAN": {
    "latitude": -7.1420843,
    "longitude": 112.4132861,
    "precision": "exact",
    "displayName": "Gardu Induk Lamongan · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV LAWANG": {
    "latitude": -7.8491537,
    "longitude": 112.6903161,
    "precision": "exact",
    "displayName": "Gardu Induk Lawang · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV LUMAJANG": {
    "latitude": -8.1285868,
    "longitude": 113.2125297,
    "precision": "exact",
    "displayName": "Gardu Induk Lumajang · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV MANISREJO": {
    "latitude": -7.6405783,
    "longitude": 111.5481388,
    "precision": "exact",
    "displayName": "Gardu Induk Manisrejo · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV MANYAR": {
    "latitude": -7.1286653,
    "longitude": 112.6129559,
    "precision": "exact",
    "displayName": "Gardu Induk Manyar · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV MLIWANG": {
    "latitude": -6.8190853,
    "longitude": 111.8917729,
    "precision": "exact",
    "displayName": "Gardu Induk Mliwang · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV MOJOAGUNG": {
    "latitude": -7.5905015,
    "longitude": 112.3436021,
    "precision": "exact",
    "displayName": "Gardu Induk Mojoagung · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NEGARA": {
    "latitude": -8.3643071,
    "longitude": 114.6604167,
    "precision": "exact",
    "displayName": "Gardu Induk Negara · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NEWNGANJUK": {
    "latitude": -7.6111102,
    "longitude": 111.9127501,
    "precision": "exact",
    "displayName": "Gardu Induk Nganjuk · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NEWPACITAN": {
    "latitude": -8.1828052,
    "longitude": 111.1127119,
    "precision": "exact",
    "displayName": "Gardu Induk Pacitan · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NEWPANDAAN": {
    "latitude": -7.6386798,
    "longitude": 112.7022268,
    "precision": "exact",
    "displayName": "Gardu Induk Pandaan · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NEWPONOROGO": {
    "latitude": -7.8699119,
    "longitude": 111.493692,
    "precision": "exact",
    "displayName": "Gardu Induk Ponorogo · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NEWPORONG": {
    "latitude": -7.5321017,
    "longitude": 112.7014694,
    "precision": "exact",
    "displayName": "Gardu Induk Porong · PLN · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NEWTULUNGAGUNG": {
    "latitude": -8.0579255,
    "longitude": 111.9185767,
    "precision": "exact",
    "displayName": "Gardu Induk Tulungagung · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NEWWLINGI": {
    "latitude": -8.1424885,
    "longitude": 112.2470543,
    "precision": "exact",
    "displayName": "Gardu Induk Wlingi · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NGAGEL": {
    "latitude": -7.2878641,
    "longitude": 112.7494164,
    "precision": "exact",
    "displayName": "GIS Ngagel · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NGAWI": {
    "latitude": -7.4074015,
    "longitude": 111.456673,
    "precision": "exact",
    "displayName": "Gardu Induk Ngawi · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV NGORO": {
    "latitude": -7.5565676,
    "longitude": 112.6123492,
    "precision": "exact",
    "displayName": "Gardu Induk Ngoro · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PACIRAN": {
    "latitude": -6.8911786,
    "longitude": 112.4340955,
    "precision": "exact",
    "displayName": "Gardu Induk Paciran · PLN' · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PADANG SAMBIAN": {
    "latitude": -8.66671,
    "longitude": 115.18672,
    "precision": "exact",
    "displayName": "Gardu Induk Padang Sambian · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PAKIS": {
    "latitude": -7.9681786,
    "longitude": 112.6800911,
    "precision": "exact",
    "displayName": "Gardu Induk Pakis · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PAMEKASAN": {
    "latitude": -7.1473406,
    "longitude": 113.4554587,
    "precision": "exact",
    "displayName": "Gardu Induk Pamekasan · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PAYANGAN": {
    "latitude": -8.4437349,
    "longitude": 115.2418723,
    "precision": "exact",
    "displayName": "Gardu Induk Payangan · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PECATU": {
    "latitude": -8.8199045,
    "longitude": 115.141764,
    "precision": "exact",
    "displayName": "GIS Pecatu · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PEMARON": {
    "latitude": -8.1362077,
    "longitude": 115.0598573,
    "precision": "exact",
    "displayName": "Pemaron · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PEMECUTAN KELOD": {
    "latitude": -8.6899883,
    "longitude": 115.1889171,
    "precision": "exact",
    "displayName": "Gardu Induk Pemecutan Kelod · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PERAK": {
    "latitude": -7.2084732,
    "longitude": 112.7226485,
    "precision": "exact",
    "displayName": "Gardu Induk Perak · PT Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PESANGGARAN": {
    "latitude": -8.718465,
    "longitude": 115.2109985,
    "precision": "exact",
    "displayName": "Gardu Induk Pesanggaran · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PETROKIMIA": {
    "latitude": -7.1521041,
    "longitude": 112.6350038,
    "precision": "exact",
    "displayName": "Gardu Induk Petrokimia · PLN · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PIER": {
    "latitude": -7.6280055,
    "longitude": 112.8136468,
    "precision": "exact",
    "displayName": "Gardu Induk PIER · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PLTU PACITAN": {
    "latitude": -8.1828052,
    "longitude": 111.1127119,
    "precision": "exact",
    "displayName": "Gardu Induk Pacitan · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PROBOLINGGO": {
    "latitude": -7.764306,
    "longitude": 113.2129987,
    "precision": "exact",
    "displayName": "Gardu Induk Probolinggo · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PUGER": {
    "latitude": -8.3428726,
    "longitude": 113.4946865,
    "precision": "exact",
    "displayName": "Gardu Induk Puger · PLN",
    "query": "OpenStreetMap power=substation"
  },
  "150KV PURWOSARI": {
    "latitude": -7.7681915,
    "longitude": 112.7600324,
    "precision": "exact",
    "displayName": "Gardu Induk Purwosari · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV REJOSO": {
    "latitude": -7.694427,
    "longitude": 112.9652908,
    "precision": "exact",
    "displayName": "Gardu Induk Rejoso · PLN · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV RUNGKUT": {
    "latitude": -7.34124,
    "longitude": 112.7464057,
    "precision": "exact",
    "displayName": "Gardu Induk Rungkut · PT Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SAMBIKEREP": {
    "latitude": -7.2629789,
    "longitude": 112.643688,
    "precision": "exact",
    "displayName": "Gardu Induk Sambikerep · PT Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SAMPANG": {
    "latitude": -7.1793718,
    "longitude": 113.2388356,
    "precision": "exact",
    "displayName": "Gardu Induk Sampang · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SANUR": {
    "latitude": -8.6748353,
    "longitude": 115.2529902,
    "precision": "exact",
    "displayName": "Gardu Induk Sanur · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SAWAHAN": {
    "latitude": -7.254851,
    "longitude": 112.7136802,
    "precision": "exact",
    "displayName": "GIS Sawahan · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SEDATI": {
    "latitude": -7.3954237,
    "longitude": 112.7619281,
    "precision": "exact",
    "displayName": "Gardu Induk Sedati · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SEGOROMADU": {
    "latitude": -7.1910154,
    "longitude": 112.6441444,
    "precision": "exact",
    "displayName": "Gardu Induk Segoromadu · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SEKARPUTIH": {
    "latitude": -7.4689363,
    "longitude": 112.4612508,
    "precision": "exact",
    "displayName": "Gardu Induk Sekarputih · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SENGKALING": {
    "latitude": -7.9044061,
    "longitude": 112.5751518,
    "precision": "exact",
    "displayName": "Gardu Induk Sengkaling · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SIDOARJO": {
    "latitude": -7.4956032,
    "longitude": 112.7001384,
    "precision": "exact",
    "displayName": "Gardu Induk Sidoarjo · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SIMPANG": {
    "latitude": -7.2644502,
    "longitude": 112.751445,
    "precision": "exact",
    "displayName": "GIS Simpang · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SITUBONDO": {
    "latitude": -7.7172192,
    "longitude": 114.0187725,
    "precision": "exact",
    "displayName": "Gardu Induk Situbondo · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SUKOLILO": {
    "latitude": -7.2912313,
    "longitude": 112.7700935,
    "precision": "exact",
    "displayName": "Gardu Induk Sukolilo · PT Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SUMENEP": {
    "latitude": -7.0089593,
    "longitude": 113.8357366,
    "precision": "exact",
    "displayName": "Gardu Induk Sumenep · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SURABAYA SELATAN": {
    "latitude": -7.3082801,
    "longitude": 112.810791,
    "precision": "exact",
    "displayName": "Gardu Induk Surabaya Selatan · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SURYAZIGZAG": {
    "latitude": -7.7544994,
    "longitude": 112.0230796,
    "precision": "exact",
    "displayName": "Gardu Induk Surya · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV SUTAMI": {
    "latitude": -8.1605679,
    "longitude": 112.4443796,
    "precision": "exact",
    "displayName": "Gardu Induk Sutami · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV TANDES": {
    "latitude": -7.2559257,
    "longitude": 112.68509,
    "precision": "exact",
    "displayName": "Gardu Induk Tandes · PT Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV TANGGUL": {
    "latitude": -8.1774329,
    "longitude": 113.4510308,
    "precision": "exact",
    "displayName": "Gardu Induk Tanggul · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV TANJUNG AWAR AWAR": {
    "latitude": -8.3659874,
    "longitude": 116.1533108,
    "precision": "exact",
    "displayName": "Gardu Induk Tanjung · PLN",
    "query": "OpenStreetMap power=substation"
  },
  "150KV UJUNG": {
    "latitude": -7.2100236,
    "longitude": 112.7441726,
    "precision": "exact",
    "displayName": "Gardu Induk Ujung · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV UNDAAN": {
    "latitude": -7.2547303,
    "longitude": 112.7425068,
    "precision": "exact",
    "displayName": "GIS Undaan · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "150KV WARU": {
    "latitude": -7.3477513,
    "longitude": 112.7080811,
    "precision": "exact",
    "displayName": "Gardu Induk Waru · PT Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV WLINGI": {
    "latitude": -8.1424885,
    "longitude": 112.2470543,
    "precision": "exact",
    "displayName": "Gardu Induk Wlingi · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "150KV WONOKROMO": {
    "latitude": -7.3025386,
    "longitude": 112.7408629,
    "precision": "exact",
    "displayName": "GIS Wonokromo · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "30KV DOLOPO": {
    "latitude": -7.746899,
    "longitude": 111.527401,
    "precision": "exact",
    "displayName": "Gardu Induk Dolopo · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV AJINOMOTO": {
    "latitude": -7.4478542,
    "longitude": 112.4456333,
    "precision": "exact",
    "displayName": "Gardu Induk Ajinomoto · PLN · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "70KV BANARAN": {
    "latitude": -7.836582,
    "longitude": 112.0326284,
    "precision": "exact",
    "displayName": "Gardu Induk Banaran · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV BANGUN": {
    "latitude": -7.4799516,
    "longitude": 112.5687678,
    "precision": "exact",
    "displayName": "Gardu Induk Bangun · PLN · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "70KV BLIMBING": {
    "latitude": -7.9392027,
    "longitude": 112.6422237,
    "precision": "exact",
    "displayName": "Gardu Induk Blimbing · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV BLITAR BARU": {
    "latitude": -8.0738106,
    "longitude": 112.1859944,
    "precision": "exact",
    "displayName": "Gardu Induk Blitar · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV BUDURAN": {
    "latitude": -7.422985,
    "longitude": 112.721433,
    "precision": "exact",
    "displayName": "Gardu Induk Buduran · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV CARUBAN": {
    "latitude": -7.5331041,
    "longitude": 111.6476194,
    "precision": "exact",
    "displayName": "Gardu Induk Caruban · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV DOLOPO": {
    "latitude": -7.746899,
    "longitude": 111.527401,
    "precision": "exact",
    "displayName": "Gardu Induk Dolopo · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV DRIYOREJO": {
    "latitude": -7.3687406,
    "longitude": 112.5998469,
    "precision": "exact",
    "displayName": "Gardu Induk Driyorejo · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV GAMPINGAN": {
    "latitude": -8.1936256,
    "longitude": 112.556007,
    "precision": "exact",
    "displayName": "Gardu Induk Gampingan · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV KEBONAGUNG": {
    "latitude": -8.0214043,
    "longitude": 112.6169953,
    "precision": "exact",
    "displayName": "Gardu Induk Kebonagung · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV KERTOSONO": {
    "latitude": -7.6148983,
    "longitude": 112.0978296,
    "precision": "exact",
    "displayName": "Gardu Induk Kertosono · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV MAGETAN": {
    "latitude": -7.6439487,
    "longitude": 111.3298131,
    "precision": "exact",
    "displayName": "Gardu Induk Magetan · PLN · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "70KV MANISREJO": {
    "latitude": -7.6405783,
    "longitude": 111.5481388,
    "precision": "exact",
    "displayName": "Gardu Induk Manisrejo · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "70KV MANYAR": {
    "latitude": -7.1286653,
    "longitude": 112.6129559,
    "precision": "exact",
    "displayName": "Gardu Induk Manyar · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV MASPION": {
    "latitude": -7.3752637,
    "longitude": 112.7205279,
    "precision": "exact",
    "displayName": "Gardu Induk Maspion · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "70KV MASPIONSBM": {
    "latitude": -7.3752637,
    "longitude": 112.7205279,
    "precision": "exact",
    "displayName": "Gardu Induk Maspion · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "70KV MIWON": {
    "latitude": -7.3667921,
    "longitude": 112.6090244,
    "precision": "exact",
    "displayName": "Gardu Induk Miwon · PLN · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "70KV MRANGGEN": {
    "latitude": -7.5882017,
    "longitude": 111.4377165,
    "precision": "exact",
    "displayName": "Gardu Induk Mranggen · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "70KV NGANJUK": {
    "latitude": -7.6111102,
    "longitude": 111.9127501,
    "precision": "exact",
    "displayName": "Gardu Induk Nganjuk · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV PARE": {
    "latitude": -7.8548222,
    "longitude": 112.1693775,
    "precision": "exact",
    "displayName": "Gardu Induk Pare · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV PLOSO": {
    "latitude": -7.4727673,
    "longitude": 112.231223,
    "precision": "exact",
    "displayName": "Gardu Induk Ploso · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV PLTA TULUNGAGUNG": {
    "latitude": -8.0579255,
    "longitude": 111.9185767,
    "precision": "exact",
    "displayName": "Gardu Induk Tulungagung · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV POLEHAN": {
    "latitude": -7.984544,
    "longitude": 112.6425304,
    "precision": "exact",
    "displayName": "Gardu Induk Polehan · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV PONOROGO": {
    "latitude": -7.8699119,
    "longitude": 111.493692,
    "precision": "exact",
    "displayName": "Gardu Induk Ponorogo · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV SEGOROMADU": {
    "latitude": -7.1910154,
    "longitude": 112.6441444,
    "precision": "exact",
    "displayName": "Gardu Induk Segoromadu · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV SEKARPUTIH": {
    "latitude": -7.4689363,
    "longitude": 112.4612508,
    "precision": "exact",
    "displayName": "Gardu Induk Sekarputih · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV SENGKALING": {
    "latitude": -7.9044061,
    "longitude": 112.5751518,
    "precision": "exact",
    "displayName": "Gardu Induk Sengkaling · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV TARIK": {
    "latitude": -7.4594712,
    "longitude": 112.4972413,
    "precision": "exact",
    "displayName": "Gardu Induk Tarik · Perusahaan Listrik Negara · distribution",
    "query": "OpenStreetMap power=substation"
  },
  "70KV TRENGGALEK": {
    "latitude": -8.0614461,
    "longitude": 111.7100733,
    "precision": "exact",
    "displayName": "Gardu Induk Trenggalek · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV TULUNGAGUNG": {
    "latitude": -8.0579255,
    "longitude": 111.9185767,
    "precision": "exact",
    "displayName": "Gardu Induk Tulungagung · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV TUREN": {
    "latitude": -8.1720466,
    "longitude": 112.6870038,
    "precision": "exact",
    "displayName": "Gardu Induk Turen · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "70KV WLINGI": {
    "latitude": -8.1424885,
    "longitude": 112.2470543,
    "precision": "exact",
    "displayName": "Gardu Induk Wlingi · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "GITET 500KV GRATI": {
    "latitude": -7.6540006,
    "longitude": 113.0242632,
    "precision": "exact",
    "displayName": "GITET Grati · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "GITET 500KV KEDIRI": {
    "latitude": -7.8399999,
    "longitude": 112.0366518,
    "precision": "exact",
    "displayName": "GITET Kediri · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "GITET 500KV KRIAN": {
    "latitude": -7.3448845,
    "longitude": 112.6032308,
    "precision": "exact",
    "displayName": "GITET Krian · Perusahaan Listrik Negara · transmission",
    "query": "OpenStreetMap power=substation"
  },
  "GITET 500KV NGIMBANG": {
    "latitude": -7.2879426,
    "longitude": 112.189255,
    "precision": "exact",
    "displayName": "GITET Ngimbang · PLN · transmission",
    "query": "OpenStreetMap power=substation"
  }
};
